package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setBid(java.lang.Integer bid) {
		set("bid", bid);
	}
	
	public java.lang.Integer getBid() {
		return getInt("bid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}
	
	public java.lang.String getImg() {
		return getStr("img");
	}

	public void setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
	}
	
	public java.lang.String getLatitude() {
		return getStr("latitude");
	}

	public void setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
	}
	
	public java.lang.String getLongitude() {
		return getStr("longitude");
	}

	public void setDuty(java.lang.String duty) {
		set("duty", duty);
	}
	
	public java.lang.String getDuty() {
		return getStr("duty");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
