package com.wts.entity.model;

import com.wts.entity.base.BaseBureau;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bureau extends BaseBureau<Bureau> {
	public static final Bureau dao = new Bureau().dao();
}
