package com.wts.entity.model;

import com.wts.entity.base.BaseContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contact extends BaseContact<Contact> {
	public static final Contact dao = new Contact().dao();
}
