package com.wts.entity.model;

import com.wts.entity.base.BaseCounty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class County extends BaseCounty<County> {
	public static final County dao = new County().dao();
}
