package com.wts.entity.model;

import com.wts.entity.base.BaseWrong;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wrong extends BaseWrong<Wrong> {
	public static final Wrong dao = new Wrong().dao();
}
